version: "3.8"

services:
  api:
    container_name: winzo-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    command: node dist/server.js
